apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkins-crt
spec:
  secretName: jenkins-crt
  dnsNames:
  - example.mydomain.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.mydomain.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer